export const ExpenseImages = {
  car_ic: require('./car.png'),
  tax_ic: require('./tax.png'),
  bill_ic: require('./bill.png'),
  food_ic: require('./food.png'),
  sport_ic: require('./sport.png'),
  house_ic: require('./house.png'),
  beauty_ic: require('./beauty.png'),
  health_ic: require('./health.png'),
  social_ic: require('./social.png'),
  shopping_ic: require('./shopping.png'),
  clothing_ic: require('./clothing.png'),
  glossary_ic: require('./glossary.png'),
  insurance_ic: require('./insurance.png'),
  telephone_ic: require('./telephone.png'),
  education_ic: require('./education.png'),
  electronics_ic: require('./electronics.png'),
  transporting_ic: require('./transporting.png'),
  entertainment_ic: require('./entertainment.png'),
};
